### ISSUE TITLE
What are your plans?

### ISSUE THREAD

**Issue by kazimir-malevich** [tsenart/trunks#1]
I used to use Vegata quite extensively at the BBC many years ago. What are your plans for trunks? Writing clean tests in Rust or a dynamic glue language and sophisticated reporting plus distribution in what ever form you care to mention would be a big plus. I don't mind helping with this.

**Comment by tsenart** [comment]
Hey! Roadmap isn't set in stone! Can you elaborate on what your vision in on the topics you mentioned? Happy to discuss :-)
